### ISSUE TITLE
Cannot be used from a service context

### ISSUE THREAD

**Issue by rambo** [jacklinquan/usb4a#1]
https://github.com/jacklinquan/usb4a/blob/master/usb4a/usb.py#L55 fails when used in a service (https://python-for-android.readthedocs.io/en/latest/services/) and user cannot just monkeypatch that:

```
09-29 15:48:53.919 27737 27754 I GNSSService: Hello world! from gnssserv_entrypoint.py
09-29 15:48:54.651 27737 27754 I GNSSService: *** monkey-patching usb4a context ***
09-29 15:48:54.652 27737 27754 I GNSSService: Traceback (most recent call last):
09-29 15:48:54.653 27737 27754 I GNSSService:   File "/home/rambo/devel/augnss_buildozer/android/app/gnssserv_entrypoint.py", line 22, in <module>
09-29 15:48:54.653 27737 27754 I GNSSService:   File "jnius/jnius_export_class.pxi", line 130, in jnius.jnius.MetaJavaClass.__setattr__
09-29 15:48:54.653 27737 27754 I GNSSService:   File "jnius/jnius_export_class.pxi", line 485, in jnius.jnius.JavaField.__set__
09-29 15:48:54.653 27737 27754 I GNSSService:   File "jnius/jnius_export_class.pxi", line 662, in jnius.jnius.JavaField.write_static_field
09-29 15:48:54.654 27737 27754 I GNSSService:   File "jnius/jnius_conversion.pxi", line 414, in jnius.jnius.convert_python_to_jobject
09-29 15:48:54.654 27737 27754 I GNSSService:   File "jnius/jnius_utils.pxi", line 205, in jnius.jnius.check_assignable_from
09-29 15:48:54.654 27737 27754 I GNSSService: jnius.jnius.JavaException: Invalid instance of 'org/kivy/android/PythonService' passed for a 'org/kivy/android/PythonActivity'
````

**Comment by jacklinquan** [comment]
Thanks @rambo !
I will deal with your pull request as soon as possible.
